version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Temp123*
    ports:
     - "1433:1433"
    restart: always
    volumes:
     - F:/Infrastructure/ImageVolume/SqlServer/data:/var/opt/mssql/data
     - F:/Infrastructure/ImageVolume/SqlServer/secrets:/var/opt/mssql/secrets
     - F:/Infrastructure/ImageVolume/SqlServer/log:/var/opt/mssql/log