version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Local123*
    ports:
     - "1434:1433"
    restart: always
    volumes:
     - C:/Users/igrwi/Work/Infrastructure/DockerVolume/SqlServer2019/data:/var/opt/mssql/data
     - C:/Users/igrwi/Work/Infrastructure/DockerVolume/SqlServer2019/secrets:/var/opt/mssql/secrets
     - C:/Users/igrwi/Work/Infrastructure/DockerVolume/SqlServer2019/log:/var/opt/mssql/log